### ISSUE TITLE
[FEATURE REQUEST] Add section

### ISSUE THREAD

**Issue by sbrunner** [prospector-dev/prospector#710]
Add a way to be able to add some configuration to a part of the files. 

Example of configuration:
```yaml
sections:
  tests:
    patterns:
      - ^tests?/?
      - /tests?(/|$)
      - .*/tests(/|$)
      - (^|/)test_[_a-zA-Z0-9]+.py$
      - (^|/)[_a-zA-Z0-9]+_tests?.py$
      - (^|/)tests?.py
    bandit:
      run: False
```

In a section, we will have the patterns and the tool's configuration.

Requires #709
